set_action_timer:
  name: Set Action Timer
  description: Create a new disposable action timer 
  fields:
    duration:
      name: Duration
      description: Duration in seconds.
      required: true
      default: 60
      selector:
        number:
          min: 1
          max: 86400
          unit_of_measurement: seconds
          mode: box
    action:
      name: Action
      description: "Pick what should happen when the timer ends (Device, Entity, or Service)."
      required: false # Support for simple 'Egg Timers'
      selector:
        action: {} 
    run_on_power_restore:
      name: Run on power restore
      description: Whether to run the action if the timer expired while Home Assistant was offline.
      required: false
      default: false
      selector:
        boolean: {}

cancel_action_timer:
  name: Cancel Action Timer
  description: Cancel an active action timer using its generated sensor id
  fields:
    action_timer_id:
      name: Action Timer Entity ID
      required: true
      selector:
        entity: 
          filter:
            domain: sensor
            integration: action_timer